// Generated by CoffeeScript 1.9.3
(function() {
  var IO, cuddly, debug, events, os, pkg, stamp;

  events = ['dev', 'ops', 'csr'];

  stamp = function() {
    return (new Date()).toISOString();
  };

  cuddly = function(tag, url) {
    var event, host, i, len, ref, res, socket;
    if (url == null) {
      url = process.env.CUDDLY_URL;
    }
    host = (ref = process.env.CUDDLY_HOST) != null ? ref : os.hostname();
    socket = null;
    res = {};
    for (i = 0, len = events.length; i < len; i++) {
      event = events[i];
      res[event] = function(error, data) {
        if (data == null) {
          data = {};
        }
        data.error = error;
        data.application = tag;
        data.host = host;
        data.stamp = stamp();
        return Promise.resolve().then(function() {
          if (socket == null) {
            socket = IO(url);
          }
          return socket.emit("report_" + event, data);
        })["catch"](function(error) {
          return debug("socket: " + error);
        });
      };
    }
    return res;
  };

  cuddly.events = events;

  module.exports = cuddly;

  IO = require('socket.io-client');

  os = require('os');

  pkg = require('./package.json');

  debug = (require('debug'))(pkg.name);

}).call(this);

//# sourceMappingURL=index.js.map
